# Generated by Django 4.1.5 on 2023-01-31 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveySchemaModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="SurveyResultModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.JSONField()),
                (
                    "survey_schema_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.surveyschemamodel",
                    ),
                ),
            ],
        ),
    ]
