# Generated by Django 4.1.5 on 2023-02-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyschemamodel",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyschemamodel",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
